version: "3"

services:
  animore:
    build: .
    entrypoint: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    env_file:
      - .env.local
    external_links:
      - "host.docker.internal"
